### ISSUE TITLE
Documentation not in line with Ionic 7

### ISSUE THREAD

**Issue by Webrow** [ionic-team/pwa-elements#117]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Documentation states to put platformBrowserDynamic().bootstrapModule(AppModule) in your main.ts file.   
Module files have been removed, and when creating a new ionic project the file is not exported as an @NGModule

**Expected behavior:**
No idea, My structural knowledge isn't sound enough to know how to solve this.

**Steps to reproduce:**
New ionic tabs starter will create a main.ts file with a bootstrapApplication method. And will not have an exported member called AppModule, therefor annot register the module with the platformBrowserDynamic.

**Comment by sean-perkins** [comment]
Hello 👋 I am going to close this issue. We updated the `ionic start `command so that it will default to generate Angular starters with modules. Developers can opt-in to the standalone usage if they desire.
