### ISSUE TITLE
CameraSource.Camera does not work as expected

### ISSUE THREAD

**Issue by brune83** [ionic-team/pwa-elements#132]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://chat.stenciljs.com

**Current behavior:**
Calling Camera.getPhoto function, even if the source parameter is set with CameraSource.Camera value, in the bottom left of the camera window the "Pick image" button is shown, making the user able to choose a picture from the gallery.

**Expected behavior:**
I expect that if the source parameter is set with CameraSource.Camera value, the user is not able to choose a picture from the gallery.

**Related code:**

```
Camera.getPhoto({
	...
	source: CameraSource.Camera,
	...
});
```

**Comment by jcesarmobile** [comment]
pwa-elements now supports disabling that icon, but has to be implemented on the Camera plugin, it's been requested already:
https://github.com/ionic-team/capacitor-plugins/issues/749
