### ISSUE TITLE
stencil version provides a broken acorn release

### ISSUE THREAD

**Issue by cdarken** [ionic-team/pwa-elements#15]
Updated my app to @ionic/angular v4.1.0. The app was originally started with v4.0.0-beta17 and with capacitor enabled.
Updated all the packages to the latest versions, but when running serve this error pops up:

```
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/es5/ionic.core.js 6:2160
[ng] Module parse failed: Unexpected token (6:2160)                       
[ng] You may need an appropriate loader to handle this file type.         
```

Mike pointed me to this bug: https://github.com/ionic-team/ionic/issues/17225

The output of `npm ls acorn' with ionic-pwa-elements installed:

```
└─┬ @ionic/pwa-elements@1.0.1
  └─┬ @stencil/core@0.17.2   
    └─┬ jsdom@11.11.0        
      ├── acorn@5.7.3        
      └─┬ acorn-globals@4.3.0
        └── acorn@6.1.1      
```

After I remove it (and all the capacitor related packages) and run npm install again, it works.

**Comment by jcesarmobile** [comment]
can you try with 1.1.0?

**Comment by jcesarmobile** [comment]
Closing as latest version doesn't use @ionic/core
