### ISSUE TITLE
No Ionic/Angular Support or Documentation

### ISSUE THREAD

**Issue by iaguilera14** [ionic-team/pwa-elements#23]
**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
There is no documentation or support for integrating with Ionic4/Angular. The documentation on Stencil's Website references functions (defineCustomElements) that seem to be removed from the 1.1.0 release of pwa-elements. 

https://stenciljs.com/docs/angular

There seems to be no clear path to integrating this with your core products of Ionic/Angular and Capacitor. I have no problem modifying and/or importing different things into my app but this is more like shooting in the dark. 

**Expected behavior:**
I would expect there to be at least a short guide of how to integrate this with Ionic/Angular. 

**Steps to reproduce:**
Try and use pwa-elements with Ionic/Angular and Capacitor.

**Comment by dotNetkow** [comment]
Hi @iaguilera14, you're in luck! We recently published a [Capacitor + Ionic Angular guide](https://capacitor.ionicframework.com/docs/guides/ionic-framework-app) that includes adding Camera functionality (via PWA Elements). Enjoy.

**Comment by iaguilera14** [comment]
@dotNetkow Your guide is out of date with your current release. I believe 1.2.0 no longer requires the script tag on HTML. You guys should really think about updating the guide with content from the stencil docs and stuff that has been on stackoverflow. 

https://stackoverflow.com/questions/54589782/how-to-include-ionic-pwa-elements-in-an-ionic4-angular-build

https://stenciljs.com/docs/angular/

I was able to get it integrated following the links above.

**Comment by oori** [comment]
@iaguilera14  and what about the [modals](https://github.com/jcesarmobile/capacitor-angular-camera-sample/issues/1)?    that issue is also mentioned in the [stackoverflow](https://stackoverflow.com/a/54910400/205049) solution you mentioned.

**Comment by jcesarmobile** [comment]
The PWA Elements guide on Capacitor's website has been updated with instructions about how to use it with Angular and React (https://capacitor.ionicframework.com/docs/pwa-elements)
The README has a wrong link, but I just sent a PR updating it.

**Comment by iaguilera14** [comment]
@oori It all seems to work now with the latest versions.

**Comment by iaguilera14** [comment]
@jcesarmobile Yes I saw that! This is great thanks!

**Comment by Dipak84** [comment]
Can not override "camera-modal.css" CSS property in our custom CSS.
