### ISSUE TITLE
No option to choose existing photo

### ISSUE THREAD

**Issue by iaguilera14** [ionic-team/pwa-elements#30]
**I'm submitting a ...** 
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Camera Plugin does not support loading photo from library or prompting user to choose. This works on native but is not implemented currently with pwa-elements. 

**Expected behavior:**
`const image = await Camera.getPhoto({
      quality: 75,
      allowEditing: true,
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Photos
    });`
This should load photo library for user to choose photo.

`const image = await Camera.getPhoto({
      quality: 75,
      allowEditing: true,
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Prompt
    });`
This should prompt user to choose between take photo and choose photo.

**Other information:**
Testing on:
`"@ionic/pwa-elements": "^1.2.7",
"@capacitor/cli": "1.0.0",
    "@capacitor/core": "1.0.0",
    "@capacitor/ios": "^1.0.0",`

**Comment by jcesarmobile** [comment]
There is a Capacitor issue already for this 
https://github.com/ionic-team/capacitor/issues/490
