### ISSUE TITLE
version 1.4.0 broken? 

### ISSUE THREAD

**Issue by jabiinfante** [ionic-team/pwa-elements#37]
Hi!

I am using @ionic/pwa-elements inside an angular application.

This is the code to define custom elements inside muy app (as documented [here](https://capacitor.ionicframework.com/docs/pwa-elements/)):

```ts
import { defineCustomElements } from '@ionic/pwa-elements/loader';

defineCustomElements(window);
```

Every was working as expected with version 1.3.0... but I just accidentally update and build is broken:

```bash
WARNING in ./src/main.ts 12:0-20
"export 'defineCustomElements' was not found in '@ionic/pwa-elements/loader'

ERROR in -/node_modules/@ionic/pwa-elements/loader/index.es2017.mjs
Module not found: Error: Can't resolve '../dist/esm/loader.mjs' in '-/node_modules/@ionic/pwa-elements/loader'
ERROR in -/node_modules/@ionic/pwa-elements/loader/index.es2017.mjs
Module not found: Error: Can't resolve '../dist/esm/polyfills/index.js' in '-/node_modules/@ionic/pwa-elements/loader'
ERROR in chunk vendor [initial]
vendor.49badd78888d593567e4.js
-/node_modules/@ionic/pwa-elements/loader/index.es2017.mjs
Cannot read property 'isProvided' of null
```

I have downloaded, built and linked from a local folder version 1.4.0, and everything works as expected... so I would say it is a problem with the package uploaded to npm.

I have found some folders are missing inside v1.4.0:

From my local build inside **./dist/**:
```
 $ tree -L 1
.
├── cjs
├── collection
├── esm
├── esm-es5
├── index.js
├── index.mjs
├── ionicpwaelements
├── ionicpwaelements.js
└── types
```

Inside npm downloaded v1.4.0 **./dist/** folder:

```
$ tree  -L 1
.
├── collection
├── ionicpwaelements
├── ionicpwaelements.js
└── types
```

Or maybe I am missing something else...
Thanks in advance

**Comment by MaikeMota** [comment]
I'm with problems here to!
I updated from 1.3.0 to resolve the problem mentioned in the issue [#36 ](https://github.com/ionic-team/pwa-elements/issues/36).

**Comment by rdlabo** [comment]
+1

**Comment by bashoogzaad** [comment]
+1

**Comment by JoshuvaGeorge03** [comment]
How to solve this issue?

**Comment by mlynch** [comment]
Hmm, that function is definitely there, checking to see if something changed in Stencil recently

**Comment by mlynch** [comment]
Okay my bad, 1.4.1 fixes it. Must not have built it first
