### ISSUE TITLE
 CameraSource.Prompt configuration is not working

### ISSUE THREAD

**Issue by appdevworx** [ionic-team/pwa-elements#39]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
The camera modal is opening without prompt in the web browser. however in android is working as expected
 
**Expected behavior:**
when camera options configuration include "source: CameraSource.Prompt", a prompt shall appear asking whether to take picture or from photos  

**Steps to reproduce:**
I am using 
Ionic 4 + Angular + Capacitor + pwa-elements
1- configure Camera Options with source: CameraSource.Prompt
2- ionic serve
3- open the camera modal by executing Plugins.Camera.getPhoto
4- Camera Modal will open directly without prompt
-->

**Related code:**
const image = await Plugins.Camera.getPhoto({
          quality: 50,
          source: CameraSource.Prompt,
          correctOrientation: true,
          width: 600,
          resultType: CameraResultType.DataUrl,
        });

**Comment by RangerRick** [comment]
It appears that setting `source` doesn't work at all.  When I try to pass `source: CameraSource.Photos` it still pops up the "take a photo" UI.

**Comment by BluebambooSRL** [comment]
Same as RangerRick source: CameraSource.Photos not working

**Comment by shadowboxingskills** [comment]
+1

**Comment by andrewrains** [comment]
Unfortunately, can't take a photo directly in iOS Safari PWA (issue #64), and can't prompt for the alternatives.

**Comment by jcesarmobile** [comment]
it's being tracked here https://github.com/ionic-team/capacitor-plugins/issues/493
will be fixed on camera plugin once https://github.com/ionic-team/capacitor-plugins/pull/487 gets merged
