### ISSUE TITLE
Library should be beta

### ISSUE THREAD

**Issue by wallaceturner** [ionic-team/pwa-elements#56]
There are serious shortcomings in this library and as such it should be marked as beta and/or the shortcoming should be stated on the README.

The image appearing inverted is a complete blocker and the fact the library does not work when run as a standalone PWA (home screen launch)
Also the forward facing camera is the default view and cannot be changed.
I have wasted significant time investing in this library only to learn of the bugs

As per your docs:
```
Currently, the project offers a quality in-app Camera experience using getUserMedia, with support for multiple cameras and with automatic handling of image data.
```

`quality in-app Camera experience` - i beg to differ

**Comment by mlynch** [comment]
Closing as not a very productive issue, but will look into some of those individual challenges
