### ISSUE TITLE
bug: Camera modal shows 'undefined' on footer, next to shutter

### ISSUE THREAD

**Issue by Sebxx** [ionic-team/pwa-elements#58]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.5.1

  @capacitor/core 1.5.1

  @capacitor/ios 1.5.1

  Found 7 Capacitor plugins for ios:
    cordova-plugin-camera (4.1.0)
    cordova-plugin-device (2.0.2)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-ionic-webview (4.1.3)
    cordova-plugin-splashscreen (5.0.2)
    cordova-plugin-statusbar (2.4.2)
    cordova-plugin-whitelist (1.3.3)
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Electron
- [x] Web

## Current Behavior

When the function "getPhoto" is executed, the camera modal is opened as expected. But the world "undefined" is placed on the camera-footer element, just next to the shutter.
Overmore, when the user takes the photo and clicks the "retake" button, the camera modal goes totally black.
Screenshots attached.

## Expected Behavior

The camera modal shouldn't have an "undefined" message next to the buttons.
If the user clicks the "retake" button, the camera should open again and let to take the photo.

## Sample Code or Sample Application Repo

`async takePhoto() {
    this.photo = '';
    this.showButton = false;

    try {

      const image = await Plugins.Camera.getPhoto({
        quality: 72,
        allowEditing: false,
        resultType: CameraResultType.DataUrl,
        source: CameraSource.Camera
      });

      if (!image)
        return this.nav.navigateBack('/start');

      this.photo = this.domSanitizer.bypassSecurityTrustResourceUrl(image && (image.dataUrl));
      this.showButton = this.photo ? true : false;
      return;
    } catch (error) {
      console.log(error);
      return this.nav.navigateBack('/start');
    }

  }`

## Reproduction Steps

In the first screenshot the camera works properly but with the 'undefined' message.
In the second screenshot, the user clicked the 'retake' button and then the camera went all black.

Those screenshots where taken on Google Chrome from and Android device. But it also reproduces in any browser in mobile and in desktop.

![Screenshot_2020-03-19-15-52-25-831_com android chrome](https://user-images.githubusercontent.com/8863114/77114071-e6500b00-69f9-11ea-9ceb-4af104555062.png)
![Screenshot_2020-03-19-15-52-40-364_com android chrome](https://user-images.githubusercontent.com/8863114/77114084-eb14bf00-69f9-11ea-978f-7d9498cb1f2e.png)

## Other Technical Details

`npm --version` output: 6.13.7

`node --version` output: v12.14.0

`pod --version` output (iOS issues only):

**Comment by stepankouba** [comment]
same problem with me, same version of Capacitor. It disappears when photo taken. So far the idea is: What about this line: https://github.com/ionic-team/pwa-elements/blob/974cc2f99f53c8a2e48c8631c04073259319f43e/src/components/camera/camera.tsx#L324

**Comment by kaushikji007** [comment]
Issue is still there I can see the commented code but undefined text is visible in footer section of camera popup

**Comment by jcesarmobile** [comment]
The fix has not been released

**Comment by listenerxdw** [comment]
has it been released? i got the exactly same issue

**Comment by Douxim** [comment]
same issue... thanks

**Comment by alejandroquadri** [comment]
Same problem

**Comment by LauraRamirez22** [comment]
same problem

**Comment by garryalfa** [comment]
hi, is the fixed already release?
