### ISSUE TITLE
Camera freeze in iOS safari browser (PWA)

### ISSUE THREAD

**Issue by dodomui** [ionic-team/pwa-elements#64]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 insert the output from npm list @stencil/core here
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Camera freeze after camera launch for 1-2 seconds on iOS PWA.
Need press on the safari video recording button twice (disable and enable back the video recording) to make it working properly.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by mlynch** [comment]
Which version of iOS?

**Comment by Alexookah** [comment]
same happens to me. ios 14.0

**Comment by shadowboxingskills** [comment]
+1 (iOS 14.1, iPad Pro)

**Comment by dotNetkow** [comment]
Can confirm running [Ionifits app](https://github.com/ionic-team/ionifits) in Safari browser or as installed PWA.

Specs:
- iOS 14.2 (latest, currently)
- PWA Elements v3.0.1
- Cap iOS 2.4.3 (2.4.4. is latest)
- Ionifits app code: https://github.com/ionic-team/ionifits
- On the web: https://ionifits.ionicframework.com
- Camera usage code (getPhoto): [view this line](https://github.com/ionic-team/ionifits/blob/main/src/app/services/expense.service.ts#L43)

To repro, open [https://ionifits.ionicframework.com](https://ionifits.ionicframework.com) on an iOS device. On login screen, take SKIP button, tap Expenses tab, tap FAB button at bottom to open modal, then tap the Camera FAB to open the device camera. The front facing camera loads and the image freezes right away. after about 2 seconds, the camera window turns to black. 

Running on the web (desktop), get this error in console: _Uncaught (in promise) TypeError: Cannot read property 'length' of undefined  at o.initPhotoCapabilities_

**Comment by andrewrains** [comment]
If helpful in finding the issue: 
- OS 14.2 (latest, currently)
- PWA Elements v3.0.1
- Cap iOS 2.4.4

When it freezes, if you tap the red camera icon in Safari's search/URL base to turn the camera off, then back on again, everything works as expected.

**Comment by mrzyte** [comment]
As mentioned in the other thread [https://github.com/ionic-team/capacitor/issues/3656](url), iOS 14.3 seems to solve this issue. I guess we have to wait and the problem will sort out itself.

**Comment by mikeapr4** [comment]
I upgraded from iPad OS 14.0.1 to 14.4 and this solved the issue, I think this issue can be safely closed.

The link to the other thread is: https://github.com/ionic-team/capacitor/issues/3656 (something is wrong with the link above)

I couldn't find anything official from Apple about this, the Apple developer thread is: https://developer.apple.com/forums/thread/667453

**Comment by jcesarmobile** [comment]
closing since it was an iOS issue and was fixed by apple
