### ISSUE TITLE
The default camera should be Rear not Front

### ISSUE THREAD

**Issue by mtsmachado8** [ionic-team/pwa-elements#70]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
The default camera should be Rear not Front

**Expected behavior:**
The default camera should be Rear not Front

**Steps to reproduce:**
Tested on galaxy S20+

**Related code:**

```
import {
  Camera,
  CameraResultType,
  CameraSource,
  CameraDirection,
} from '@capacitor/core';

const image = await Camera.getPhoto({
        resultType: CameraResultType.DataUrl,
        source: CameraSource.Camera,
        direction: CameraDirection.Rear,
        quality: 100,
      });
      const imageDataUrl = image.dataUrl;
```
![image](https://user-images.githubusercontent.com/11022437/99710541-72ca3600-2a7f-11eb-9263-a918c4514823.png)

**Comment by mtsmachado8** [comment]
#69 solves it

**Comment by jcesarmobile** [comment]
This project is separate from Capacitor, despite Capacitor's Cameara depends on it, so the default doesn't have to be the same.
I've sent a PR that allows to configure the camera to use, another one is needed in Camera plugin to configure the default.
