### ISSUE TITLE
A /undefined request is made when taking a photo

### ISSUE THREAD

**Issue by Spielboerg** [ionic-team/pwa-elements#85]
ionic/pwa-elements version:

```
@ionic/pwa-elements@3.0.2
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
After taking a photo but before the confirmation screen is visible, a `/undefined` network request is made. This happens because a variable used to set a background image is undefined for a short time:

<img width="605" alt="undefined bug" src="https://user-images.githubusercontent.com/7893762/123428955-a8f80700-d5c6-11eb-99d2-35b303026f0c.png">

**Expected behavior:**
No `/undefined` request is made.

**Steps to reproduce:**
1. Open the dev tools and keep an eye on the network requests
2. Open camera
2. Take a photo
3. A `/undefined` request is made
 
**Related code:**
[camera.tsx, line 436](https://github.com/ionic-team/pwa-elements/blob/master/src/components/camera/camera.tsx#L436)
```tsx
<div class="accept">
  <div
    class="accept-image"
    style={{
      backgroundImage: `url(${this.photoSrc})`,
      ...acceptStyles
    }} />
</div>
```

**Related pull requests:**
Since I looked at the code for the first time today and have no overview/understanding of the whole project, I don't know if the if clause in [camera.tsx, line 431](https://github.com/ionic-team/pwa-elements/blob/master/src/components/camera/camera.tsx#L431) is wrong (fixed in version 2) or if it should be caught if `this.photoSrc` is not set (fixed in version 2).

Version 1: https://github.com/ionic-team/pwa-elements/pull/86
Version 2: https://github.com/ionic-team/pwa-elements/pull/87

**Comment by jcesarmobile** [comment]
closing as https://github.com/ionic-team/pwa-elements/pull/87 was merged
