### ISSUE TITLE
Question: is that possible to force the use of PWA elements on Android Capacitor App ?

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/pwa-elements#89]
# Problem

The native Camera API make hybrid apps crash on many Android devices
cf 
- https://github.com/apache/cordova-plugin-camera/issues/660
- https://github.com/apache/cordova-plugin-camera/issues/665
- https://github.com/ionic-team/capacitor/issues/2712

# Need

Using WebRTC image capture is more stable on Android devices, so is there a way to force use of PWA elements on Android environment ?

**Comment by jcesarmobile** [comment]
You can use PWA elements directly instead of using Capacitor Camera plugin, check Camera's plugin web implementation if you have doubts/problems.
But you can't force Camera plugin to use the web implementation, unless you fork the plugin and remove the native implementation.

**Comment by Aarbel** [comment]
@jcesarmobile Camera is really not stable for many Android devices (cf the Camera bugs I listed above).

If I provide a fork to Camera plugin with this possible option (ie "don't use camera plugin on Android") will you merge it ?

**Comment by jcesarmobile** [comment]
no

**Comment by Aarbel** [comment]
@jcesarmobile this issue concerns nearly 50% of Android users, but it's hard to reproduce on simulator as it's a RAM problem.

Most of Android devices have now a too big Camera, in comparison with how the internal specific OS uses the RAM to take pictures. I will test back Camera plugin, but that's really a big thing now in the hybrid ecosystem. Native Cordova Camera plugin makes app crash really often on these devices.
