### ISSUE TITLE
Show loading during image capture

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/pwa-elements#92]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 insert the output from npm list @stencil/core here
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

It takes about 2 seconds until the photo is really taken. Clicking the capture button and viewing the actual photo. It even looks like not the first frame is capture but the last so I need to freeze while it does whatever it does during capture process. A loading or label "Please stay still for a few seconds" would be way better for the user experience.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by jcham** [comment]
This and #108 are the same bug.
